-- Auto-generated by scripts/sync-d1-articles.ts
-- 2026-04-25T07:19:22.706Z
-- 6 articles

BEGIN;

INSERT OR REPLACE INTO articles (slug, title, category, published, author, read_time, hero_image, last_synced) VALUES ('best-gentle-cleansers-under-20000', '2만원 이하 진짜 순한 클렌저 7가지', 'beauty', '2026-04-25', 'Saint-Rémy Editors', 6, '/images/articles/best-gentle-cleansers-under-20000/hero.jpg', 1777101562702);
INSERT OR REPLACE INTO articles (slug, title, category, published, author, read_time, hero_image, last_synced) VALUES ('sunscreen-best-5', '선크림 BEST 5', 'beauty', '2026-04-24', 'Saint-Rémy Editors', 5, '/images/articles/sunscreen-best-5/hero.jpg', 1777101562703);
INSERT OR REPLACE INTO articles (slug, title, category, published, author, read_time, hero_image, last_synced) VALUES ('deal-radar-2026-04-w4', '이번 주 딜 레이더 — 2026 4월 4주차', 'deal', '2026-04-24', 'Saint-Rémy Editors', 4, '/images/articles/deal-radar-2026-04-w4/hero.jpg', 1777101562703);
INSERT OR REPLACE INTO articles (slug, title, category, published, author, read_time, hero_image, last_synced) VALUES ('best-desk-lamps-top-5', '재택근무자용 책상 조명 5가지', 'desk', '2026-04-25', 'Saint-Rémy Editors', 5, '/images/articles/best-desk-lamps-top-5/hero.svg', 1777101562704);
INSERT OR REPLACE INTO articles (slug, title, category, published, author, read_time, hero_image, last_synced) VALUES ('parents-day-gift-best-4', '어버이날 선물 BEST 4', 'gift', '2026-04-24', 'Saint-Rémy Editors', 6, '/images/articles/parents-day-gift-best-4/hero.svg', 1777101562705);
INSERT OR REPLACE INTO articles (slug, title, category, published, author, read_time, hero_image, last_synced) VALUES ('duel-1-airpods-pro-3-vs-galaxy-buds-4-pro', 'AirPods Pro 3 vs Galaxy Buds 4 Pro', 'style', '2026-04-24', 'Saint-Rémy Editors', 7, '/images/articles/duel-1-airpods-vs-galaxy-buds/hero.jpg', 1777101562706);

INSERT OR REPLACE INTO products (id, slug, name, brand, category, related_article_slug, affiliate_url, last_synced) VALUES ('9259bb3b4f3a00c2', 'best-gentle-cleansers-under-20000-9259bb3b', '올리브영에서 보기 →', NULL, 'beauty', 'best-gentle-cleansers-under-20000', '{"oliveyoung":"https://oy.run/9uDXGglNezcTVz"}', 1777101562702);
INSERT OR REPLACE INTO products (id, slug, name, brand, category, related_article_slug, affiliate_url, last_synced) VALUES ('70adc3b313bc2aa6', 'best-gentle-cleansers-under-20000-70adc3b3', '올리브영에서 보기 →', NULL, 'beauty', 'best-gentle-cleansers-under-20000', '{"oliveyoung":"https://oy.run/aZHujahOJoWyQ1"}', 1777101562702);
INSERT OR REPLACE INTO products (id, slug, name, brand, category, related_article_slug, affiliate_url, last_synced) VALUES ('60eee24d81ef91f0', 'best-gentle-cleansers-under-20000-60eee24d', '쿠팡에서 보기 →', NULL, 'beauty', 'best-gentle-cleansers-under-20000', '{"coupang":"https://link.coupang.com/a/evRGwh"}', 1777101562702);
INSERT OR REPLACE INTO products (id, slug, name, brand, category, related_article_slug, affiliate_url, last_synced) VALUES ('0d22c36b6f86e542', 'best-gentle-cleansers-under-20000-0d22c36b', '올리브영에서 보기 →', NULL, 'beauty', 'best-gentle-cleansers-under-20000', '{"oliveyoung":"https://oy.run/eWio2RrA0Sjvo3"}', 1777101562702);
INSERT OR REPLACE INTO products (id, slug, name, brand, category, related_article_slug, affiliate_url, last_synced) VALUES ('a08e88d5f3ec2566', 'best-gentle-cleansers-under-20000-a08e88d5', '올리브영에서 보기 →', NULL, 'beauty', 'best-gentle-cleansers-under-20000', '{"oliveyoung":"https://oy.run/3cLsi5eOeD5H6z"}', 1777101562702);
INSERT OR REPLACE INTO products (id, slug, name, brand, category, related_article_slug, affiliate_url, last_synced) VALUES ('215f26a683a009e2', 'best-gentle-cleansers-under-20000-215f26a6', '쿠팡에서 보기 →', NULL, 'beauty', 'best-gentle-cleansers-under-20000', '{"coupang":"https://link.coupang.com/a/evRNLB"}', 1777101562702);
INSERT OR REPLACE INTO products (id, slug, name, brand, category, related_article_slug, affiliate_url, last_synced) VALUES ('eafc6f39e9ffb3bb', 'best-gentle-cleansers-under-20000-eafc6f39', '올리브영에서 보기 →', NULL, 'beauty', 'best-gentle-cleansers-under-20000', '{"oliveyoung":"https://oy.run/nrLF3hLC3Bh8vd"}', 1777101562702);
INSERT OR REPLACE INTO products (id, slug, name, brand, category, related_article_slug, affiliate_url, last_synced) VALUES ('d22b16a5f2348332', 'sunscreen-best-5-d22b16a5', '올리브영에서 보기 →', NULL, 'beauty', 'sunscreen-best-5', '{"oliveyoung":"https://oy.run/CjhoT5eKX2h86C"}', 1777101562703);
INSERT OR REPLACE INTO products (id, slug, name, brand, category, related_article_slug, affiliate_url, last_synced) VALUES ('0e0e9443c2ad5a73', 'sunscreen-best-5-0e0e9443', '올리브영에서 보기 →', NULL, 'beauty', 'sunscreen-best-5', '{"oliveyoung":"https://oy.run/EDxJUJflJFlhHH"}', 1777101562703);
INSERT OR REPLACE INTO products (id, slug, name, brand, category, related_article_slug, affiliate_url, last_synced) VALUES ('ec1914be46233281', 'sunscreen-best-5-ec1914be', '올리브영에서 보기 →', NULL, 'beauty', 'sunscreen-best-5', '{"oliveyoung":"https://oy.run/uSyEdXmG8Yq6y3"}', 1777101562703);
INSERT OR REPLACE INTO products (id, slug, name, brand, category, related_article_slug, affiliate_url, last_synced) VALUES ('03f76d9fab37612b', 'sunscreen-best-5-03f76d9f', '올리브영에서 보기 →', NULL, 'beauty', 'sunscreen-best-5', '{"oliveyoung":"https://oy.run/39ibT5eFPurAHX"}', 1777101562703);
INSERT OR REPLACE INTO products (id, slug, name, brand, category, related_article_slug, affiliate_url, last_synced) VALUES ('7ce9404117f4e6c0', 'sunscreen-best-5-7ce94041', '올리브영에서 보기 →', NULL, 'beauty', 'sunscreen-best-5', '{"oliveyoung":"https://oy.run/7tv3Rkf14iAdjD"}', 1777101562703);

COMMIT;

-- 6 articles, 12 products